# Generated by Django 3.2 on 2022-08-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20220824_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='bprice',
        ),
    ]
