# Generated by Django 3.2 on 2022-08-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_remove_bookinfo_bprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
