# Generated by Django 3.2 on 2022-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0007_alter_bookinfo_btitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='hname',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
