# Generated by Django 3.2 on 2022-08-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0009_alter_heroinfo_hcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='hcomment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
