# Generated by Django 3.2 on 2022-08-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0014_areas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
